packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  js-yaml@<3.15.0: '>=3.15.0'
  multer@>=1.0.0 <2.2.0: '>=2.2.0'
  multer@>=2.0.0-alpha.1 <2.2.0: '>=2.2.0'
  postcss@<8.5.10: '>=8.5.10'
